### ISSUE TITLE
How to get all submissions of a subreddit between two specific dates ?

### ISSUE THREAD

**Issue by kayson123** [thatJavaNerd/JRAW#100]
I have tried looking at the javadoc but there does not seem to have such function.
For example, I want to get all submissions from /r/Starbucks between 1/1/2015 to 1/12/2015. Is it possible to do so using JRAW ?

**Comment by kayson123** [comment]
any update on this ? anyone ?

**Comment by fbis251** [comment]
It doesn't look like this is supported via reddit's API:
https://www.reddit.com/dev/api

You might want to paginate all the posts in the subreddit and do some custom filtering on the Submissions that are returned.

**Comment by thatJavaNerd** [comment]
It is possible, and described on the [reddit wiki](https://www.reddit.com/wiki/search#wiki_cloudsearch_syntax).

>To see it in action here is a link that searches /r/MusicGuides between July 04,2013 & July 05,2013 [`timestamp:1372982400..1373068800`](https://www.reddit.com/r/MusicGuides/search?rank=title&q=timestamp%3A1372982400..1373068800&restrict_sr=on&syntax=cloudsearch)
Notice the &syntax=buttsearch at the end of the url which enables the timestamp searching feature.

However JRAW does not currently support cloudsearch syntax. The patch I'm working on right now addresses this and should be out within the next day or two.

**Comment by kayson123** [comment]
@thatJavaNerd great. very looking forward to this useful feature. Thanks!

**Comment by thatJavaNerd** [comment]
From the same wiki page:

>Tip: Since search results are limited to 1000 results, you can divide your query into different time periods to get past this limit using Cloudsearch Syntax.

**Comment by thatJavaNerd** [comment]
See commit [`676ea11`](https://github.com/thatJavaNerd/JRAW/commit/676ea11a91d4b233a39e7f21915ba940cd1d4796).

Here's how you can use it in the next release:

```java
SubmissionSearchPaginator p = new SubmissionSearchPaginator(reddit, "timestamp:1420070400..1421020800");
p.setSyntax(SubmissionSearchPaginator.SearchSyntax.CLOUDSEARCH);
Listing<Submission> submissions = p.next();
```
