### ISSUE TITLE
java.lang.ClassNotFoundException: com.squareup.okhttp.Authenticator [1.8.0]

### ISSUE THREAD

**Issue by tuskiomi** [thatJavaNerd/JRAW#101]
Authenticator error caused by missing JARs. tried on both JAR release and maven build.

Stacktrace:

Exception in thread "main" java.lang.NoClassDefFoundError: com/squareup/okhttp/Authenticator
	at net.dean.jraw.RedditClient.<init>(RedditClient.java:73)
	at com.tuskiomi.ReDefine.Start.main(Start.java:27)
Caused by: java.lang.ClassNotFoundException: com.squareup.okhttp.Authenticator
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 2 more

Relevant lines[72-74]:
    public RedditClient(UserAgent userAgent) {
        this(userAgent, new OkHttpAdapter());
    }

**Comment by tuskiomi** [comment]
import is as follows: import net.dean.jraw.http.OkHttpAdapter;

**Comment by thatJavaNerd** [comment]
How are you including the Jar?

**Comment by tuskiomi** [comment]
In eclipse via the build path. It appears in the referenced library section. No other jars are included. All classes are non-statically imported.

**Comment by thatJavaNerd** [comment]
Specifically, what Jar are you using? The normal `JRAW-<version>.jar` does not include any dependencies. Use `JRAW-<version>-fat.jar`.

I would recommend using a build tool such as Maven or Gradle.

**Comment by tuskiomi** [comment]
I tried both the maven and web release. Will try the fatty and report back.

**Comment by tuskiomi** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
this is the new error that I get under the same code

**Comment by thatJavaNerd** [comment]
The link the error gives you tells you exactly how to solve your problem.

>This error is reported when the `org.slf4j.impl.StaticLoggerBinder` class could not be loaded into memory. This happens when no appropriate SLF4J binding could be found on the class path. Placing one (and only one) of *slf4j-nop.jar*, *slf4j-simple.jar*, *slf4j-log4j12.jar*, *slf4j-jdk14.jar* or *logback-classic.jar* on the class path should solve the problem.

Basically, JRAW uses the SLF4J API (`slf4j-api.jar`) but leaves it up to the person using the library to attach their own SLF4J binding. To ignore all logging done by JRAW and get rid of the error message, include `slf4j-nop.jar` in your classpath. To get rid of the error and show JRAW logging, include `slf4j-simple.jar`, `slf4j-log4j12.jar`, etc.

As this is no longer related to JRAW, I will be closing the issue.
