### ISSUE TITLE
OAuthHelper says it is not authorized during RedditClient.authenticate()

### ISSUE THREAD

**Issue by jabzaVR** [thatJavaNerd/JRAW#102]
When I call `RedditClient.authenticate()`, I get an exception stating `OAuthHelper says it is not authorized`. However, *immediately* before that, I log the response of `OAuthHelper.getAuthStatus()` and it shows `AUTHORIZED`. Any ideas what the problem may be?

**Comment by thatJavaNerd** [comment]
Please include the relevant code
