### ISSUE TITLE
In the setFlair Method in ModerationManager, what is an example of this method?

### ISSUE THREAD

**Issue by tuskiomi** [thatJavaNerd/JRAW#104]
specifically, the flair template and the Json Node. I can initiate a Json node, so I plugged in my (Subreddit).getDataNode() to no avail.

**Comment by thatJavaNerd** [comment]
Can you provide the relevant code?

**Comment by tuskiomi** [comment]
RedditClient rc = new RedditClient((UserAgent));
ModerationManager modmanager = new ModerationManager(rc);
Subreddit mod = rc.getSubreddit("(subreddit)");
FlairTemplate dTemp = new FlairTemplate(mod.getDataNode());
modmanager.setFlair("(Subreddit) ", dTemp, "1.0","(Username)");
