### ISSUE TITLE
redirectUrl for installedApp

### ISSUE THREAD

**Issue by jorgegil96** [thatJavaNerd/JRAW#109]
What am i supposed to pass as redirectUrl when creating a Credentials object?

**Comment by fbis251** [comment]
![client ID vs secret](https://cloud.githubusercontent.com/assets/1300530/6812112/f777f98c-d229-11e4-8fb3-a1b699c6c9de.png)

Client ID is in green
secret is in red, but if the type of app you created is "installed app" then reddit will NOT provide a secret in your app preferences screen. Only the client ID will be available.

Redirect URL is what you're looking to pass in to JRAW

**Comment by jorgegil96** [comment]
Thanks! I didn't know about 127.0.0.1/localhost
