### ISSUE TITLE
Skip stickied submission?

### ISSUE THREAD

**Issue by Orbyt** [thatJavaNerd/JRAW#110]
Is there a way to skip a stickied post in a subreddit? Currently using this:

```java
SubredditPaginator sp = new SubredditPaginator(redditClient);

    sp.setLimit(2);
    sp.setSorting(Sorting.HOT);
    sp.setTimePeriod(TimePeriod.DAY);

    sp.setSubreddit("a_subreddit");

    sp.next(true);
    Listing<Submission> list = sp.getCurrentListing();
```

I know theres the isStickied(); method, but is there a way to just skip downloading a stickied submission so I dont have to go through the list testing for isStickied()?

**Comment by thatJavaNerd** [comment]
I don't believe so. AFAIK the only time reddit shows stickied submissions is when sorting by "hot," so choosing another sort would fix this issue. But if you absolutely need hot sorting, I think you're out of luck.

**Comment by Orbyt** [comment]
Interesting. For now just filtering it out, so gonna close this. Hopefully this is implemented into the reddit api in the future.
