### ISSUE TITLE
Get a submissions comments by submission id?

### ISSUE THREAD

**Issue by Orbyt** [thatJavaNerd/JRAW#111]
Is it possible to get the comments of a submissing using a Submission Id? Currently, I'm looping through the Submissions returned from the api call and storing certain fields into my own objects. 

I know the Submission class has a getComments() method, but because i'm using my own objects for items, I cant use it. My thinking was that instead, I could extract the id of the Submission using getId() and storing that in my objects, but im not sure if its possible or not to get comments using a submissions id.

 Is this possible?

**Comment by thatJavaNerd** [comment]
[`RedditClient.getSubmission`](https://thatjavanerd.github.io/JRAW/docs/git/net/dean/jraw/RedditClient.html#getSubmission(net.dean.jraw.http.SubmissionRequest)) is what you're looking for.
