### ISSUE TITLE
redditClient.authenticate(authData); returns an nullpointer

### ISSUE THREAD

**Issue by Martacus** [thatJavaNerd/JRAW#115]
`	static UserAgent myUserAgent = UserAgent.of("desktop", "martacus.mart.bot", "v0.1", "Martacus");
	static RedditClient redditClient = new RedditClient(myUserAgent);
	static Credentials credentials = Credentials.script("USER", "PASS", "CLIENTID", "SECRET");
	
	
	public static void main(String[] args) throws DiscordException, NetworkException, OAuthException{	
		OAuthData authData = redditClient.getOAuthHelper().easyAuth(credentials);
		redditClient.authenticate(authData);
		redditClient.me();
	}`

This is my code, and this is the Error:

Exception in thread "main" java.lang.NullPointerException
	at net.dean.jraw.http.oauth.OAuthData.getScopes(OAuthData.java:57)
	at net.dean.jraw.RedditClient.authenticate(RedditClient.java:114)
	at martacus.mart.bot.Main.main(Main.java:37)

line 37 being: 		redditClient.authenticate(authData);

I dont know why, but it seems the scopes are empty. I did as the quickstart says.
And the credentials info is valid.

**Comment by thatJavaNerd** [comment]
What version of JRAW are you using?

**Comment by Martacus** [comment]
0.8.0

**Comment by thatJavaNerd** [comment]
All tests passed when I ran them again at a detached HEAD at v0.8.0. Please make sure that the app you have created at [/prefs/apps](https://www.reddit.com/prefs/apps) is a "personal use script," and not an "installed app."

**Comment by CKalnasy** [comment]
Also having the same issue on 0.8.0 with a personal use script
