### ISSUE TITLE
Sidebar explanation

### ISSUE THREAD

**Issue by kakai248** [thatJavaNerd/JRAW#117]
I need an explanation in how is the sidebar working.

According to the Endpoints file, there is no implementation for that feature. However, when I obtain a subreddit with `Subreddit sub = client.getSubreddit("pics")` I am then able to do `sub.getSidebar()`. But the reddit documentation says that the endpoint `/r/[subreddit]/about` gives a description and not the sidebar, which are different things according to [this](https://www.reddit.com/r/changelog/comments/tztot/reddit_change_subreddits_now_have_a_public/).

What am I missing?

Thank you

**Comment by zglazer** [comment]
The current sidebar (as in `sub.getSidebar()` ) implementation returns the information from in the description node of a `/r/[subreddit]/about` request. There is no current implementation for a request to`/r/[subreddit]/sidebar`. The sidebar as you see when visiting a subreddit in your browser is the same as information returned in a call to `sub.getSidebar()`. 

The link you refer to notes an addition of a new node entitled `public_description` which is a brief description of the subreddit as seen on [reddit.com/r/subreddits](url).
