### ISSUE TITLE
Getting more comments of a thread with many comments results in too long URL exception

### ISSUE THREAD

**Issue by Azzurite** [thatJavaNerd/JRAW#119]
For example, getting comments from [this thread](https://www.reddit.com/r/AskReddit/comments/46n0zc/what_secret_do_you_hide_from_your_family_and_will/) will produce a request (in 0.8.0) that has a length of 72824 characters, at which point the reddit API returns "414 Request-URI Too Large".

**Comment by JJWTimmer** [comment]
Same problem. API docs state: Up to 20 ids at a time for /morechildren.

**Comment by ccrama** [comment]
If this is the case, is there really any way to fix this issue short of limiting it to 20 ids?

**Comment by zglazer** [comment]
You can just hit the /morechildren endpoint over and over, retrieving only 20 at a time. That ends up being an expensive operation so maybe we need a boolean to express whether the user wants all the comments or just the first 20.

Thoughts? @thatJavaNerd

**Comment by ccrama** [comment]
We could also turn it into a POST request which would totally avoid this issue, the comment here is incorrect 

https://github.com/thatJavaNerd/JRAW/blob/280c3d289863cabb8576dd1d992f1fb0fd737a85/src/main/java/net/dean/jraw/models/CommentNode.java#L420

**Comment by thatJavaNerd** [comment]
This was a surprisingly simple fix. @ccrama had the right fix I believe.

**Comment by ccrama** [comment]
@thatJavaNerd you beat me to it! Was about to create a PR. It should also fix #120

**Comment by thatJavaNerd** [comment]
@ccrama. It appears to have. I'll close it then.
