### ISSUE TITLE
Bad request when loading more comments on some threads

### ISSUE THREAD

**Issue by kakai248** [thatJavaNerd/JRAW#120]
I found a problem while loading more comments in [this thread](https://www.reddit.com/r/AskReddit/comments/48fv1i/what_poor_decision_will_you_likely_make_today/). The problem is actually while loading more root comments. It gives a `net.dean.jraw.http.NetworkException: Request returned non-successful status code: 400`.

But this is only happens in some threads.

**Comment by thatJavaNerd** [comment]
Possibly related to #119

**Comment by thatJavaNerd** [comment]
#119 seemed to have fixed this issue.
