### ISSUE TITLE
The release does not have the LOCK enumerated value in the Endpoints enum

### ISSUE THREAD

**Issue by bolt2strike** [thatJavaNerd/JRAW#122]
Endpoints.LOCK does not exist although it should and is in the gen folder of the repo

**Comment by zglazer** [comment]
I see `Endpoints.LOCK` right [here](https://github.com/thatJavaNerd/JRAW/blob/master/src/gen/java/net/dean/jraw/Endpoints.java#L160). Do you mean that an implementation for `/api/lock` does not exist?

**Comment by thatJavaNerd** [comment]
`Endpoints.LOCK` was added after the release of v0.8.0.

**Comment by bolt2strike** [comment]
I decompiled the Endpoints.class from v0.8.0 and confirmed that it does not have Enpoints.LOCK

http://pastebin.com/ckuRcWZs

**Comment by thatJavaNerd** [comment]
@bolt2strike This is correct. `LOCK` was added after the release of v0.8.0. That means that `LOCK` is not available in v0.8.0. This also means that `LOCK` will be available **in the next release**.

**Comment by bolt2strike** [comment]
Ah, sorry I now realize you said _**after v0.8.0**_, so this begs the question. When is the next release? I had to compile from source myself so I could use Enpoints.LOCK.

**Comment by thatJavaNerd** [comment]
I would like to fix some of the open issues before making a new release. That being said, it will probably be a few days before v0.9.0. Thanks for your interest in JRAW!
