### ISSUE TITLE
Sorting not possible if Paginator is not a SubredditPaginator

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#124]
According to the API docs, the "sorting" argument must be present in order to sort non-submission listings, as the /top, /new, etc. url paths do not exist for things like profiles and multireddits.

A workaround to this is to apply the "sorting" argument to the args variable in the "next()" method in Paginator.java if the paginator is not an instance of a SubredditPaginator (although this check is not necessary, Reddit will ignore the extra parameters afaik). I have tested it on my branch and it is now working properly for profiles and multireddits!

[The fix is up on my branch ](https://github.com/ccrama/JRAW/commit/9ed682becfb589ae3310eb35ddd718151d486d71)

I can make a PR to fix this if you'd like, I don't quite know if it affects anything negatively yet so might have to do some more testing

EDIT: Appears to not fix multireddit sorting, will figure out why that's not working later

EDIT 2: Fixed multireddit sorting with this

https://github.com/ccrama/JRAW/commit/5d64611bd9b489bcb4c740a83118648f07ff12c8

The path variable was never appended to the end of the string like it is in the SubredditPaginator

**Comment by kakai248** [comment]
I think it makes more sense for ```Paginator``` to not typecheck itself to see if it's a ```SubredditPaginator```. If reddit ignores the param it, we can work with that. However, maybe each paginator should know about their params and have ```Paginator``` have the common params.

**Comment by thatJavaNerd** [comment]
I agree with @kakai248. Typechecking in this case violates the abstraction that Paginator provides. It would be a better fix IMHO to make a note of it in the `SubredditPaginator` class documentation and let reddit ignore the parameter.
