### ISSUE TITLE
access_token Basic Authorization happens in 2 requests

### ISSUE THREAD

**Issue by fbis251** [thatJavaNerd/JRAW#128]
Usually when you do a request using OAuthHelper using proper credentials, JRAW will submit 2 HTTP requests to `/api/v1/access_token`

The first request will usually receive a 401 code. JRAW then retries the exact same request, but this time with an `Authorization: Basic <base64_creds>` header.

This can take a noticeable amount of time on slower networks (especially on Android devices when on mobile)

I noticed that BasicAuthenticator will act after the 401 code was received and does
[OkHttpAdapter.java#L199](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/http/OkHttpAdapter.java#L199)
`String header = response.code() == 407 ? "Proxy-Authorization" : "Authorization";`

Once it has verified that the request did not return a 407 code, it does the 2nd request will the Authorization header, which then returns a 200 code.

I may not be seeing the use case to check for a 407 header, which is why I opened this issue before opening a pull request for a patch that puts the basic auth header on the first request

Let me know what you think

**Comment by thatJavaNerd** [comment]
Good insight. Thanks for your PR!
