### ISSUE TITLE
How to sort comments from submission by New

### ISSUE THREAD

**Issue by jorgegil96** [thatJavaNerd/JRAW#130]
How do I sort a thread's comment by "new" or "top" or whatever?  

Is there a CommentPaginator or something I can use?

**Comment by zglazer** [comment]
I don't have too much experience using JRAW but I do see a CommentStream class extending Paginator. You should be able to create a comment stream and set the sorting on the stream.

```
CommentStream stream = new CommentStream(redditClient);
stream.setSorting(Sorting.NEW);
```

See PaginatorTest#309. Maybe someone else can chime in to confirm.

**Comment by jorgegil96** [comment]
Thanks for the response zglazer but I found a solution before seeing yours. Here it is:

```
SubmissionRequest.Builder b = new SubmissionRequest.Builder(sID);
b.sort(CommentSort.NEW);
SubmissionRequest sr = b.build();
Submission submission = redditClient.getSubmission(sr);
```
