### ISSUE TITLE
Next release (CloudSearch syntax support)

### ISSUE THREAD

**Issue by JJWTimmer** [thatJavaNerd/JRAW#131]
Is JRAW still maintained, given the silence since February? I would like to use it for crawler, but I would like to know the current status.

If it is still maintained, is there an ETA for the next release? I noticed the CloudSearch syntax support is added, which I am interested in to use.

**Comment by thatJavaNerd** [comment]
JRAW is still somewhat maintained. I keep an eye on it but I haven't really contributed as I've been working on another project. I should be able to push out v0.9.0 this weekend, time permitting. Thanks for your interest in JRAW!
