### ISSUE TITLE
NPE when moreChildren.getChildrenIds() returns no IDs

### ISSUE THREAD

**Issue by JJWTimmer** [thatJavaNerd/JRAW#132]
On CommentNode a NPE occurs when running loadFully, where isThreadContinuation() does moreChildren.getChildrenIds() when there are no IDs. This happens both on isThreadContinuation as well in getMoreComments in this snippet, if you fix the former:

        List<String> moreIds = moreChildren.getChildrenIds();
        StringBuilder ids = new StringBuilder(moreIds.get(0));

I can't tell what is going wrong API wise or if this is just a bug.
I tried to fix it in master, but I can't get the tests to run (gradlew test fails with a NPE on getScopes while I entered a credentials.json file, only not sure what to enter as url). I tried to add an extra expression checking if moreChildren.getChildrenIds().size() > 0.

**Comment by thatJavaNerd** [comment]
Can you provide a stacktrace and the code being executed?
