### ISSUE TITLE
Question about CommentStream

### ISSUE THREAD

**Issue by bolt2strike** [thatJavaNerd/JRAW#137]
Hello, I'm using CommentStream to iterate over a sub's comments. I was wondering how I can get the children of the comments I get from that stream. I see that Comment.getChildren() (or something like that) was removed a while ago in favor of CommentNode.getChildren() however I can't find a way to get the children or construct a comment node instance. Could someone please tell me the best way to go about this?

**Comment by ccrama** [comment]
This is not possible unless you load the comment with context from the submission

**Comment by thatJavaNerd** [comment]
It is recommended that you do not by yourself construct `CommentNode` instances, and instead let `Submission` take care of that for you. The data provided by `/r/{subreddit}/comments` only returns a single comment, not it's children. As @ccrama said, you must query the submission directly:

```java
Comment c = ...
String submissionId = c.getSubmissionId();
SubmissionRequest request = new SubmissionRequest.Builder(submissionId)
        .focus(c.getId())
        .build());
Submission s = redditClient.getSubmission(request);
```

**Comment by bolt2strike** [comment]
From `/r/{subreddit}/comments` you can press 'context' and view the rest of the comments, including the children. So then, is this a limitation of the Reddit api itself and not Jraw? If so, that's rather unfortunate.

**Comment by ccrama** [comment]
Yes, the Reddit API only returns the top level comment. You can view this if you go to https://reddit.com/r/all/comments.json, it will only show the top level comment. Where are you seeing 'context'? I only see 'View permalink' which opens the submission

**Comment by bolt2strike** [comment]
I wasn't looking at the json, the 'context' I was talking about is a button, so in the graphical form of the data. Sorry I'm commenting this from mobile and can't really post a screenshot or anything.

**Comment by ccrama** [comment]
I still don't see a "context" button on my browser, maybe it's an extension you have or I might not be understanding you correctly

**Comment by thatJavaNerd** [comment]
The "context" button is a link to the submission with the query `?context=3`. This link queries the submission directly. This is not a limitation of JRAW but rather a limitation of the reddit API.
