### ISSUE TITLE
How to fetch Banner images of subreddits?

### ISSUE THREAD

**Issue by piyush-rvc** [thatJavaNerd/JRAW#144]

**Comment by kakai248** [comment]
You can get the subreddit in the regular way:

```
RedditClient client = new RedditClient(...);
Subreddit subreddit = client.getSubreddit("food");
```

And then you can do:
```
String bannerUrl = subreddit.data("banner_img");
```

You have to use `data` because JRAW doesn't have a method to access the `banner_img` directly.

**Comment by piyush-rvc** [comment]
@kakai248  Thanks!!

**Comment by zglazer** [comment]
@piyush-rvc Can you close this issue if your question has been answered?

**Comment by konecnyna** [comment]
Is there an updated way of getting the banner image? 

I wasn't exactly sure how to access the data object from the subreddit object in the most recent build.

**Comment by mattbdean** [comment]
[Just added `Subreddit.getBannerImage()`](https://github.com/mattbdean/JRAW/commit/294aa519dee16887674ac488b03a25be55127170)

**Comment by konecnyna** [comment]
@mattbdean you're amazing! Thanks 😄
