### ISSUE TITLE
Support for variations of thumbnails

### ISSUE THREAD

**Issue by Nxt3** [thatJavaNerd/JRAW#147]
[As per this /r/redditdev post](https://www.reddit.com/r/redditdev/comments/39yr53/reddit_change_new_preview_images_available_for/), it would be awesome if JRAW supported getting the `variations` section for thumbnails (i.e. letting us use blurred thumbnails for NSFW submissions).

**Comment by thatJavaNerd** [comment]
See [Submission.getThumbnails()](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/models/Submission.java#L306) and [Thumbnails](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/models/Thumbnails.java)
