### ISSUE TITLE
Is the request to Reddit API rate limited, in case we use multiple RedditClient to make the requests?

### ISSUE THREAD

**Issue by codesForLiving** [thatJavaNerd/JRAW#150]

**Comment by thatJavaNerd** [comment]
Each RedditClient uses its own Guava RateLimiter for spacing out API requests; each client acts independently of each other. This, however will not necessarily prevent your client being ratelimited as reddit likely tracks API clients by IP as well as their OAuth2 app ID.

**Comment by codesForLiving** [comment]
@thatJavaNerd Thanks. I was not looking to bypass the API rate limit, but was worried that  my app would be banned, if I make more requests than is recommended.

**Comment by codesForLiving** [comment]
@thatJavaNerd is there any way to rate limit the requests globally?
