### ISSUE TITLE
Question about comments retreived from reddit.getSubmission

### ISSUE THREAD

**Issue by manrock007** [thatJavaNerd/JRAW#152]
I use reddit.getSubmission to retrieve comments for a given submission. On the retrieved comment nodes, if I try to node.getComment().getVote() I see the below issue

> 07-31 19:53:22.828 13684-14031/com.dreamcast.redditr E/JOBS: error while executing job com.dreamcast.redditr.ipc.GetComments@8953d98
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fasterxml.jackson.databind.JsonNode.isNull()' on a null object reference
> at net.dean.jraw.models.RedditObject._getVote(RedditObject.java:55)
> at net.dean.jraw.models.PublicContribution.getVote(PublicContribution.java:70)

Are these comments somehow now populated fully. What I need is a way to find out with comments have been voted on by the logged in user..

**Comment by thatJavaNerd** [comment]
Can you post the relevant code snippet?

**Comment by manrock007** [comment]
There you go 

public void onRun() throws Throwable {
        Log.d(TAG,"onRun" + mSubmission.getSubmission().getId() + mSubmission.getSubmission().getTitle());
//        CommentStream stream = new CommentStream(AuthenticationManager.get().getRedditClient());
        CommentNode rootNode = AuthenticationManager.get().getRedditClient().getSubmission(mSubmission.getId()).getComments();

        ArrayList<RComment> comments =prepareTree(rootNode);
        Log.d(TAG,"Preparing from " + rootNode.getTotalSize() + " to " + comments.size());
        App.getInstance().getDataModel().commentsFetched(comments,mSubmission.getSubmission().getId());
    }

**Comment by thatJavaNerd** [comment]
Can you also provide the code that throws the NPE?

**Comment by manrock007** [comment]
Oops.. there you go


// node.getComment().getVote()) generates the exception
 
```

private ArrayList<RComment> prepareTree(CommentNode node) {
        ArrayList<RComment> commentArrayList = new ArrayList<RComment>();
        commentArrayList.clear();
        if(node != null)
        {
            RComment cur_comment = new RComment();
            cur_comment.setDepth(node.getDepth());
            cur_comment.setBody(node.getComment().getBody());
            cur_comment.setNode(node);
            cur_comment.setVoteDirection(node.getComment().getVote());
            if(cur_comment.getDepth() !=0)
            {
                commentArrayList.add(cur_comment);
            }

            Iterable<CommentNode> iter = node.getChildren();
            if(node.getImmediateSize() > 0)
            {
                for (CommentNode childnode : iter)
                {
                    ArrayList<RComment> childArrayList = prepareTree(childnode);
                    for (RComment child : childArrayList) {
                        if(child.getDepth() == (cur_comment.getDepth() +1))
                            cur_comment.addChild(child);
                    }
                    commentArrayList.addAll(childArrayList);
                }
            }
        }
        return commentArrayList;
    }

```

**Comment by thatJavaNerd** [comment]
Please read the [CommentNode class documentation](https://thatjavanerd.github.io/JRAW/docs/0.9.0/net/dean/jraw/models/CommentNode.html).

>Each CommentNode has a depth, a Comment instance, and zero or more CommentNode children. Depth is defined as the level at which the comment exists. For example, a top-level reply has a depth of 1, a reply to that comment has a depth of 2, and so on.

>At the root of every comment tree there is a single root node, which represents the submission the comments belong to. This node will have a depth of 0 and its children will be top-level replies to the submission.

When you call prepareTree for the first time, `node` is the root node. The root node's Comment has no body or vote, or anything else you'd expect a normal Comment to have. That's why on the first iteration of prepareTree a NPE is thrown when you call `node.getComment().getVote()`.

You can check if a CommentNode is a root node with `node.getDepth() == 0`

See also the class definition for [`RootComment`](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/models/CommentNode.java#L558)

**Comment by manrock007** [comment]
That did it. Tested, works.. Thanks a ton. Closing
