### ISSUE TITLE
Discrepancy in submissionId from different endpoint

### ISSUE THREAD

**Issue by manrock007** [thatJavaNerd/JRAW#153]
Getting two different results for submissionId

```
1. comment.getNode().getComment().getSubmissionId() returns t3_4w85d1
2. submission.getId() returns 4w85d1
```

On reading the reddit documentation, it seems that `comment.getNode().getComment().getSubmissionId()` returns `Base36` encoded ID, where t3 means a link. Not sure why submission.getId() does not..

**Comment by zglazer** [comment]
Because getId() is inherited from Thing. From the JavaDoc:

> The Thing class is the base class for most data structures returned by the reddit API. Every Thing has an ID and a fullname (referred to as an ID36 in the Reddit source code). To construct a fullname, simply prepend tX_, where X is an integer. For a valid list of these prefixes, see [here](https://www.reddit.com/dev/api/oauth#fullnames). However, this is not the same for all classes. The Account class's fullname will return the username instead of t2_<id>.

**Comment by manrock007** [comment]
@zglazer I agree, but I still don't get why the discrepancy between the same data coming from two different requests? As i explained earlier I'm using two endpoints to get the same data, and create an ORM relationship between them. The data returned from these two endpoints is different in terms of the prefix!

**Comment by ccrama** [comment]
With submission.getId, you know it's already a t3 submission and the Reddit API returns a value without the prefix. JRAW is not removing the prefix, the API is never returning it

**Comment by manrock007** [comment]
@ccrama got it.. Thanks for the explanation!
