### ISSUE TITLE
Load reply to comment

### ISSUE THREAD

**Issue by ninja-tortoise** [thatJavaNerd/JRAW#158]
Hi 

At the minute I reply to a comment and then I want to load that comment into my commentNode tree.
I run loadMoreComments(reddit) on the parent comment node but the new comment does not load.

Is there a way to achieve this?

Thanks

**Comment by thatJavaNerd** [comment]
If you request more comments before reddit knows about the new comment, then it won't be able to tell you anything. I would suggest using the data you have to supplement what the reddit API temporarily can't provide.

**Comment by ninja-tortoise** [comment]
When I refresh my view and retrieve a new list of comments for the submission I get the reply I just made.

Looking through the library it seems to be because the id of the reply isn't added to the list of ids in the MoreChildren object in the CommentNode so it isn't retrieved as part of loadMoreComments(reddit).

This is something I would like to contribute to the library but I would like to discuss how to go about it.
I was thinking of adding another method, loadReply that would take the reply id from AccountManager.reply and add that to the children for that node.

What are your thoughts?

**Comment by ccrama** [comment]
I actually did this in my fork of JRAW, feel free to see how I did it [here](https://github.com/ccrama/JRAW/blob/master/src/main/java/net/dean/jraw/models/CommentNode.java#L285)!

**Comment by ninja-tortoise** [comment]
Ah ok! I see you talked about merging in some changes from your repo in April. 
Any update on that? 
Maybe I could start looking through yours and merge some stuff in?
This change in particular is something I need but other stuff could be useful.

**Comment by thatJavaNerd** [comment]
#159 fixes this.

**Comment by ccrama** [comment]
A lot of my commits were just to fix issues or add features to my app, but if you think they would be useful for everyone else feel free to let me know and then merge them @ninja-tortoise ! I just started classes this semester so won't have much time to contribute in the coming months, unfortunately
