### ISSUE TITLE
Credentials should use a less specific class than URL's to store the Redirect Information

### ISSUE THREAD

**Issue by dxdy-name** [thatJavaNerd/JRAW#160]
I'm happening on this problem in android. In order properly facilitate the redirect, I have to redirect to a URI with a custom scheme like: `myapp://login/`. This is all perfectly valid, both by reddits standard, and URI's. 

Unfortunately, the Credentials class handles its **redirect URI's by using the URL** class. That means I can't use this approach without either:

1) Not using a proper redirect to the browser, and instead using the less clean approach of opening a web-view and filtering all URL's.

2) Defining a custom URL scheme and its handlers to Java.

Both are possible, however it seems overly restrictive given that the standard does in fact allow for proper URI's.

This gets even more messy in the OAuthHelper where the HttpRequest is created as `HttpRequest.from("irrelevant", JrawUtils.newUrl(finalUrl))`, which is even worse to get around.

Other than that, cool library!

**Comment by fbis251** [comment]
Hey, I changed JRAW to use a URI during OAuth. You can test it out to see if it works for you:
https://github.com/thatJavaNerd/JRAW/pull/163

**Comment by thatJavaNerd** [comment]
Fixed in #163
