### ISSUE TITLE
Link of comment

### ISSUE THREAD

**Issue by Hronom** [thatJavaNerd/JRAW#162]
What is the best way to get link of comment like `permalink` on website, example:
```
https://www.reddit.com/r/worldnews/comments/53slwc/tesla_model_s_hacked_by_chinese_tech_team/d7vwl0n
```
I have tried `Comment.getUrl()` but it returns null.

**Comment by vishnumad** [comment]
I had the same issue. I just ended up doing the following.
`String url = String.format("http://www.reddit.com/r/%s/comments/%s/-/%s", comment.getSubredditName(), comment.getSubmissionId().replace("t3_", ""), comment.getId());`

**Comment by thatJavaNerd** [comment]
JRAW doesn't currently support getting the permalink, but you can accomplish the exact same thing using this URL:

```
https://www.reddit.com/comments/<thread_id>?comment=<comment_id>
```

In this case, [`https://www.reddit.com/comments/53slwc?comment=d7vwl0n`](https://www.reddit.com/comments/53slwc?comment=d7vwl0n)
