### ISSUE TITLE
Cannot find class AndroidTokenStore

### ISSUE THREAD

**Issue by Brblol** [thatJavaNerd/JRAW#164]
I am using version 0.9.0 and I am following the example [here ](https://github.com/thatJavaNerd/JRAW-Android/blob/master/example-app/src/main/java/net/dean/jrawandroidexample/App.java)
But it seems like AndroidTokenStore does not exist in the library. Has it been removed in an update? if so what is the alternative method?

**Comment by thatJavaNerd** [comment]
AndroidTokenStore belongs to JRAW-Android. Use that library to get all of the Android-related classes.

**Comment by Brblol** [comment]
Yes I see it now. thanks
