### ISSUE TITLE
Understanding the Authentication flow with AuthenticationManager

### ISSUE THREAD

**Issue by garretyoder** [thatJavaNerd/JRAW#171]
I just wanted to confirm that I'm understanding the flow here with AuthenticationManager

- Init it with something like `AuthenticationManager.get().init(redditClient, new RefreshTokenHandler(new AndroidTokenStore(context), redditClient));` whenever you init the reddit client

AndroidTokenStore.java
```java
public class AndroidTokenStore implements TokenStore {
    private SharedPreferences prefs;

    public AndroidTokenStore(Context context) {
        prefs = PreferenceManager.getDefaultSharedPreferences(context);
    }

    @Override
    public boolean isStored(String key) {
        return prefs.getString(key, null)!=null;
    }

    @Override
    public void writeToken(String key, String token) {
        prefs.edit().putString(key, token).commit();
    }

    @Override
    public String readToken(String key) throws NoSuchTokenException {
        String token = prefs.getString(key, null);
        if (token==null) throw new NoSuchTokenException("No such token");
        return token;
    }
}
```

- Use `AuthenticationManager.get().checkAuthState()` to check if there is a signed in user or not, or whether the token needs refreshed

- Use `AuthenticationManager.get().refreshAccessToken(credentials);` to refresh the token whenever it needs refreshed, or right as the app firsts starts to perform a 're login' with the saved token.

And a couple of questions
- The token needs manually refreshed, as far as I can tell AuthenticationManager doesn't have a check before any API calls to do it for you, and they expire after a hour. Is a best practice to just check the state before any calls, or just run a timer to refresh?

- Is there any performance hit from checking the state a bunch of times?

And one suggestion
- Document this flow in particular on the wiki. I'm hoping my understanding here is solid, as it _seems_ to be working, but it may help out others.

**Comment by thatJavaNerd** [comment]
In general, yes. This is JRAW's authentication flow. However, if your app is a script that runs for less than one hour `AuthenticationManager` is a little overkill.

>The token needs manually refreshed, as far as I can tell AuthenticationManager doesn't have a check before any API calls to do it for you, and they expire after a hour. Is a best practice to just check the state before any calls, or just run a timer to refresh?

It's really all up to you. If your application is only going to be making 2 or 3 requests per hour, it might be more efficient to check before you send a request. On the other hand, if your app is pushing the request limit, it might be smarter to simply catch the 401 when reddit starts crying about the expired token. I personally haven't ran into this problem. Maybe @ccrama can weigh in on how he solved it with Slide?

>Is there any performance hit from checking the state a bunch of times?

Take a look at [`AuthenticationManager.checkAuthState()`](https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/auth/AuthenticationManager.java#L69-L80). If the authentication data is valid, then the method will return quickly. If not, the method queries the `tokenHandler`, which internally uses a user-defined TokenStore. At this point, the speed at which `checkAuthState` returns is based almost entirely on the speed of the TokenStore.

PS, take a look at [JRAW-Android](https://github.com/thatJavaNerd/JRAW-Android)
