### ISSUE TITLE
What purpose does RefreshTokenHandler serve

### ISSUE THREAD

**Issue by Saketme** [thatJavaNerd/JRAW#173]
Hello, I'm fairly new to Reddit's APIs and I'm trying to understand how this library works exactly. I have so far understood the need for refreshing API keys, but I'm unable to understand what purpose does `RefreshTokenHandler` serve as compared to simply using a generic `TokenStore`?

**Comment by thatJavaNerd** [comment]
From the `RefreshTokenHandler` documentation:

>This class is a specialized implementation of TokenStore whose only objective is to store refresh tokens for various users. This class combines two sources for reading, writing, and checking: a RedditClient and a generic TokenStore. The `isStored(String)` and `readToken(String)` methods will use both sources, while `writeToken(String, String)` will only use the TokenStore. Although it is not required, it is recommended that the TokenStore source write to some place more permanent, such as a file or a database.

To put it simply, AuthenticationManager uses this class to support many user's refresh tokens.

**Comment by Saketme** [comment]
I read the documentation, but is handling refreshes for multiple users the only thing `RefreshTokenHandler` does?

**Comment by thatJavaNerd** [comment]
That's one part of it. The other feature that separates RefreshTokenHandler from other TokenStores is that RefreshTokenHandler looks at data from two sources, a RedditClient and another TokenStore. The only JRAW class to use RefreshTokenHandler is AuthenticationManager.

**Comment by Saketme** [comment]
> RefreshTokenHandler looks at data from two sources, a RedditClient and another TokenStore

Can I also ask why so?

**Comment by thatJavaNerd** [comment]
AuthenticationManager uses the RefreshTokenHandler to poll the current user's tokens. Having the RefreshTokenHandler pull from both a RedditClient and a separate TokenStore allows AuthenticationManager to know if there exists a token for a given user, either (1) being used to actively refresh a RedditClient's access token or (2) in storage.

**Comment by Saketme** [comment]
Okay got it. Do you mind if I continue asking more questions in the future, mostly because the wiki is quite limited in content.

**Comment by thatJavaNerd** [comment]
That is perfectly fine.
