### ISSUE TITLE
Is it possible to check if a comment is the root comment node?

### ISSUE THREAD

**Issue by Saketme** [thatJavaNerd/JRAW#174]
Hello. The class, `RootComment` is package local, so it's impossible to use it for checking if a comment is the root. Is there any other way around this?

**Comment by thatJavaNerd** [comment]
Why would you use RootComment? If `Comment.getDepth() == 1` then it is a top level comment.

**Comment by Saketme** [comment]
Ah sorry, I got confused with words. I actually want to check if a comment is the root node and not a top-level node.

**Comment by Saketme** [comment]
Update: Turns out I can check if the depth is 0 for the root node.
