### ISSUE TITLE
RedditClient#deauthenticate() doesn't clear the stored access tokens

### ISSUE THREAD

**Issue by Saketme** [thatJavaNerd/JRAW#184]
Please correct me if I'm doing this wrong, but looks like the access tokens stored in a `TokenHandler` never get cleared because `RedditClient#deauthenticate()` never notifies `AuthenticationManager` about it. As a result, when a new `RedditClient` object is created (e.g., when the app restarts), the user is logged back in because we still have the access token.

I will send a PR soon. Please feel free to reject it if this is incorrect.

**Update:** My PR is ready, but it's blocked on #183. You can view it separately here in the meanwhile: https://github.com/Saketme/JRAW/pull/2

**Comment by karanrajpal14** [comment]
@mattbdean is this added to 0.9.0? Because I still am facing this issue. I need to implement logout functionality for the app and it doesn't work right now. The user still remains logged in after I open the app again.
