### ISSUE TITLE
Better support for asynchronous operations

### ISSUE THREAD

**Issue by thatJavaNerd** [thatJavaNerd/JRAW#192]
JRAW v0.9 is a synchronous-first library. There is no built-in support for async/reactive programming via Future or RxJava. As @josecostamartins and @ccrama have expressed in #191, using JRAW in an Android app (or any multithreaded environment for that matter) is a hassle. To fix this, I'm considering introducing a PendingAction class:

```java
public class PendingAction<T> {
    // <constructor>
    public T get() // get the T synchronously
    public Callable<T> defer() // create a Callable for later use
}
```

Since `defer` returns a `Callable<T>`, we can easily use this in both RxJava and regular ExecutorServices.

```java
PendingAction<Subreddit> subredditAction = redditClient.subreddit("pics").about();

// With ExecutorService
Future<Subreddit> future = someExecutorService.submit(subredditAction.defer());
Subreddit pics = future.get();

// With RxJava
Single single = Single.fromCallable(action.defer()).subscribeOn(Schedulers.io());
single.subscribe((Subreddit pics) -> { /* do something with the subreddit */ });

// Or get the result synchronously
Subreddit pics = subredditAction.get();
```

Any thoughts?

**Comment by Saketme** [comment]
I personally think there is no reason for doing this. RxJava offers excellent support for converting sync. calls to async. calls by simply using `Observable.fromCallable(() -> syncCall())`. I've been using RxJava extensibly in my app and things have been great so far.

**Comment by josecostamartins** [comment]
I don't know the amount of effort needed to accomplish this task, but everybody that doesn't use RxJava will benefit from it.

In other words, if the gains exceed the work I think that it should be done.

Thanks

**Comment by Saketme** [comment]
Even If you're not using RxJava, you can still wrap the API calls in some other way, right? RxJava was just an example. If you're still using AsyncTasks (I'm sorry for you if you do) you can wrap them in your tasks.

**Comment by thatJavaNerd** [comment]
I agree with @Saketme. Synchronous operations can always be wrapped, whether that be for an event bus, RxJava, or an ExecutorService.

The PendingAction would also introduce unnecessary complexity when using the library synchronously. Code could be littered with `get()` calls.

I think Android-specific examples using RxJava, event bus, etc. would be better than implementing this change.
