### ISSUE TITLE
AuthenticationManager#checkAuthState() possibly computes AuthenticationState incorrectly for userless app

### ISSUE THREAD

**Issue by Saketme** [thatJavaNerd/JRAW#193]
So this is a bug that was introduced by me in #180. To check whether a token refresh is needed, `AuthenticationManager#checkAuthState()` gets the time at which the last token was acquired using `TokenHandler#readAcquireTimeMillis(String username)`:

```
if (reddit.isAuthenticated() && authData != null && tokenHandler.isAcquiredTimeStored(getUsername())) {
    long expirationTimeMillis = tokenHandler.readAcquireTimeMillis(getUsername()) + authData.getExpirationDurationMillis();
    if (expirationTimeMillis > System.currentTimeMillis()) {
        return AuthenticationState.READY;
    }
}
```

However, `getUsername()` is always going to return null for a userless app. This still works without crashing anywhere with an NPE because `RefreshTokenHandler#getKeyFor()` returns `refresh_token_null` instead of throwing an exception. 

One solution that I can think of right offhand will be to use a constant value instead of calling `getUsername()` in both `AuthenticationManager#checkState()` and `AuthenticationManager#refreshAccessToken()`.  

Thoughts?

**Comment by thatJavaNerd** [comment]
That is exactly what I've done for the Kotlin rewrite. `AuthManager.USERNAME_USERLESS` is used for storing any application-only data.

At this stage in the rewrite I'm not going to be accepting any PR's for the Java codebase unless it's also in issue in the Kotlin code.

**Comment by Saketme** [comment]
Good to know, thanks!
