### ISSUE TITLE
Http Client read timeout not set / cannot set said timeout without extending RedditClient. Without it application hangs.

### ISSUE THREAD

**Issue by janpetryk** [thatJavaNerd/JRAW#45]
Hello,

I encountered a bug where without read timeout set my application hangs on socketRead0. I could not set this timeout without extending your class, because OkHttpClient is not accessible from outside.

**Comment by thatJavaNerd** [comment]
Have you tried [`RestClient.setTimeoutLength()`](https://thatjavanerd.github.io/JRAW/docs/latest/net/dean/jraw/http/RestClient.html#setTimeoutLength(long))?

**Comment by janpetryk** [comment]
This method provides only connection timeout length, not read timeout.

**Comment by thatJavaNerd** [comment]
I think it would be a good idea to remove/deprecate `setTimeoutLength()` and provide a `getOkHttpClient()` method, which would allow you to configure the client directly. How do you feel about that?

**Comment by janpetryk** [comment]
It is fine by me. The question is how tightly do you want to couple your project with okhttp client.

**Comment by thatJavaNerd** [comment]
In the next release you should be able to adjust the read timeout using `reddit.getHttpAdapter().setReadTimeout(int)`.

**Comment by hzsweers** [comment]
What happened to `getOkHttpClient()`? With the new interceptors features, it would be great to be able to take advantage of that. A good use case would be with Facebook's new `Stetho` library, which plugs into it with its own interceptor: https://github.com/facebook/stetho

A good middleground would be to maybe expose this as part of HttpAdapter, but not sure if you want that to have anything specific to OkHttp.

**Comment by thatJavaNerd** [comment]
`getOkHttpClient()` was removed in favor of `getHttpAdapter()` as it decouples JRAW from any specific HTTP library. The default implementation of `HttpAdapter` (`OkHttpAdapter`) still uses OkHttp, but the the interface is written in such a way that HttpAdapters could be made for HttpComponents or some other library without an API change.

If you wanted to bring a method like `getOkHttpClient()` back, I would suggest introducing generics to HttpAdapter:

```java
public interface HttpAdapter<T> {
    // <other methods here>
    public T getNativeClient();
}
```

So then HttpAdapter could be declared like this:

```java
public class OkHttpAdapter extends HttpAdapter<OkHttpClient>
```

**Comment by hzsweers** [comment]
That seems reasonable to me. Would you be open to a pull request for that?
