### ISSUE TITLE
Forbidden Access When Getting Listing from SubredditPaginator

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#49]
I'm having an issue where I get a Network exception when running 
<code>
SubredditPaginator sub= new SubredditPaginator(reddit, "subreddit");
  return sub.next();
</code>

Stacktrace:
<code>
 Caused by: net.dean.jraw.http.NetworkException: Request returned non-successful status code: 403 Forbidden
            at net.dean.jraw.http.RestClient.execute(RestClient.java:134)
            at net.dean.jraw.RedditClient.execute(RedditClient.java:152)
            at net.dean.jraw.paginators.Paginator.next(Paginator.java:107)
            at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:44)
            at net.dean.jraw.paginators.Paginator.accumulate(Paginator.java:127)
            at net.dean.jraw.paginators.Paginator.accumulateMerged(Paginator.java:135)
</code>

From some googling, it seems as if OAuth was messed up somewhere, even though I have not implemented logging in/OAuth (yet). What could be the issue?

Thanks!

EDIT: Just FYI, I ran the code with "all" instead of "subreddit"

**Comment by thatJavaNerd** [comment]
>even though I have not implemented logging in/OAuth

The `oauth.reddit.com` domain will *always* return a 403 if you don't have a valid access token. If you don't want to implement the login functionality right now, you can use application-only OAuth, which allows you to send requests without a user context.

See [here](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2#script-and-application-only) for how to do this.

**Comment by ccrama** [comment]
Awesome. This helps a lot. Thanks for making this awesome wrapper!

**Comment by ccrama** [comment]
I am now getting an error about too many follow-up requests:
     Caused by: java.net.ProtocolException: Too many follow-up requests: 21

My code:

<code>Credentials credentials = Credentials.userlessApp("android:me.ccrama.RedditSlide:v0.1.0 (by /u/ccrama)", UUID.randomUUID());
        new AsyncLogin().execute(credentials);</code>

AsyncLogin class:
<code>private class AsyncLogin extends AsyncTask<Credentials, Void, Boolean> {
        private final ProgressDialog dialog = new ProgressDialog(Subreddit.this);

        @Override
        protected void onPostExecute(Boolean result) {
           isLoggedIn = result;
            if(result == true)
            //Load Stuff

        }

        @Override
        protected Boolean doInBackground(Credentials... creds){

            OAuthData authData = null;
            try {
                authData = reddit.getOAuthHelper().easyAuth(creds[0]);
            } catch (OAuthException e) {
                e.printStackTrace();
                return false;
            }
            reddit.authenticate(authData);
            return true;
        }

    } </code>

Am I doing something wrong, or is it just not responding in time?

Thanks

**Comment by ccrama** [comment]
Your last answer worked for non-auth users, and I implemented the code (on that page) to authenticate users who wish to login, which worked perfectly. It also brought up an issue, though. 

How do you log the user back in a second time (when the app is opened) without having to request an OAuthToken again (as in the example)? On the wiki, it states about the Refresh Token "Note that this disqualifies script and application-only apps.". 

What method to get a token works with with application-only apps (which I'm assuming means phone apps)?

**Comment by DVassilev** [comment]
@thatJavaNerd I am getting this despite oAuth working fine at other times.
