### ISSUE TITLE
Use Previously Authenticated Details to Re-Login (Application Use)

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#50]
The OAuth2 wiki page doesn't go into much detail on how to re-gain access to the previously logged-in user without having to have the user re-allow the application access to their profile.

Currently, I ask the user for a username + password, and if the UserChallengeTask completes correctly, I store the two values to re-authenticate on the next time the application is opened. I can create a new credentials object using the username + password, but how do you tell the RedditClient to log in using those details and skip the permissions screen (that they have already accepted)?

Thanks!

**Comment by thatJavaNerd** [comment]
Assuming you're using version 0.7.0.2 and you request a refresh token when you call `OAuthHelper.getAuthorizationUrl()`, you can use [`OAuthHelper.setRefreshToken(String)`](http://thatjavanerd.github.io/JRAW/docs/0.7.0.2/net/dean/jraw/http/oauth/OAuthHelper.html#setRefreshToken(java.lang.String)) followed by [`OAuthHelper.refreshToken(Credentials)`](https://thatjavanerd.github.io/JRAW/docs/0.7.0.2/net/dean/jraw/http/oauth/OAuthHelper.html#refreshToken(net.dean.jraw.http.oauth.Credentials)) to retrieve another valid access token.

**Comment by ccrama** [comment]
Thank you for the quick reply!

So I should store the username, password, and access token, then do OAuthHelper.setRefreshToken(storedtoken) and .refreshToken(Credentials.installedApp(username, password, appkey, url)?

**Comment by thatJavaNerd** [comment]
Issue referenced: #51
