### ISSUE TITLE
MoreComments

### ISSUE THREAD

**Issue by gjmills** [thatJavaNerd/JRAW#52]
The method "loadMoreComments(...) doesn't work correctly.  The new comments that are loaded aren't integrated into the tree.

(apologies if this is not the right place for this kind of feedback )

**Comment by thatJavaNerd** [comment]
Can you provide the code that's causing this issue?

**Comment by gjmills** [comment]
try{
         OAuthData authData = redditClient.getOAuthHelper().easyAuth(credentials);
             redditClient.authenticate(authData);
             Submission s = redditClient.getSubmission("2yo1ns");
             CommentNode rootNode = s.getComments();
             boolean hasFoundMore = true;
             while(hasFoundMore){
                      hasFoundMore = false;
                      Iterable<CommentNode> iterable = rootNode.walkTree();
                      for (CommentNode node : iterable) {
                          
                          if(node.hasMoreChildren()){
                             hasFoundMore = true;
                             node.loadMoreComments(redditClient);
                             System.out.println("This always prints out the same node...it never loads all the 'morecomments'..."+node.getComment().getBody()+" ");
                             break;
                         }
                     
                 }
              }
             
        }catch (Exception e){
            
              
       
        }

**Comment by gjmills** [comment]
Oops apologies for the formatting...will send as email

**Comment by gjmills** [comment]
Hi

Thanks for the quick response! Below is the code:



try{
             OAuthData authData = 
redditClient.getOAuthHelper().easyAuth(credentials);
              redditClient.authenticate(authData);
              Submission s = redditClient.getSubmission("2yo1ns");
              CommentNode rootNode = s.getComments();
              boolean hasFoundMore = true;
              while(hasFoundMore){
                       hasFoundMore = false;
                       Iterable<CommentNode> iterable = rootNode.walkTree();
                       for (CommentNode node : iterable) {

                           if(node.hasMoreChildren()){
                              hasFoundMore = true;
node.loadMoreComments(redditClient);
                              System.out.println("This always prints out the 
same node...it never loads all the 
'morecomments'..."+node.getComment().getBody()+" ");
                              break;
                          }

                  }
               }

         }catch (Exception e){


       }

**Comment by gjmills** [comment]
Hi

Apologies for the slightly unwieldy code - I have been trying all day to find a 
way of loading all the MoreComments of a submission (i.e making sure that the 
full comment tree is loaded).
  I imagine I must be  missing something basic - so sorry if this is wasting 
your time!

cheers

Gregory

**Comment by gjmills** [comment]
I think the problem is that the Comment.loadMoreComments(...) method doesn't delete the MoreComments of the Comments that are loaded.

A solution I found that seems to work is to add a single line of code (see below):


public List<CommentNode> loadMoreComments(RedditClient reddit) throws NetworkException {
        if (!hasMoreChildren())
            // Nothing to do
            return new ArrayList<>();      
        int relativeRootDepth = depth + 1;
        List<CommentNode> newRootNodes = new ArrayList<>();
        List<Thing> thingsToAdd = getMoreComments(reddit);
        this.moreChildren=null; ///ADDING THIS SEEMS TO DO THE TRICK

**Comment by thatJavaNerd** [comment]
Ah, good catch. I'll update the code and close the issue then.

**Comment by thatJavaNerd** [comment]
Fixed in commit [`93b0537`](https://github.com/thatJavaNerd/JRAW/commit/93b053749d2444dfaf460ef17d9c0d0d5de365d5)
