### ISSUE TITLE
NoClassDefFound - java.nio.charset.StandardCharsets 

### ISSUE THREAD

**Issue by papadu** [thatJavaNerd/JRAW#53]
Hi there,

I'm trying to use JRAW on android, but it crashes on any device older than android 4.4 with a NoClassDefFoundError, as it can't find the StandardCharsets Class (Which was added in API 19 https://developer.android.com/reference/java/nio/charset/StandardCharsets.html).

Is there any way to fix this?

Best Regards,
Michael.

**Comment by thatJavaNerd** [comment]
Can you provide the stack trace? Currently my best guess is that [this line](https://github.com/thatJavaNerd/JRAW/blob/b5c2796ffd5fe938fea16ae27fa9bfeec6c1ecce/src/main/java/net/dean/jraw/http/RestResponse.java#L51) is causing the error.

**Comment by papadu** [comment]
Sure thing - You appear to be right.

03-12 19:58:28.915: E/AndroidRuntime(14776): Caused by: java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.http.RestResponse.<init>(RestResponse.java:51)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.http.OkHttpAdapter.execute(OkHttpAdapter.java:62)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.http.RestClient.execute(RestClient.java:122)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.RedditClient.execute(RedditClient.java:152)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.paginators.Paginator.next(Paginator.java:107)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.paginators.SubredditPaginator.next(SubredditPaginator.java:44)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at net.dean.jraw.paginators.Paginator.next(Paginator.java:70)
03-12 19:58:28.915: E/AndroidRuntime(14776): 	at com.papadu.bassdrop.network.reddit.SubredditAsyncTask.doInBackground(SubredditAsyncTask.java:82)
