### ISSUE TITLE
Bad Request when Refreshing Token 0.7.0.3

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#57]
I'm getting the following error
`net.dean.jraw.http.NetworkException: Request returned non-successful status code: 400 Bad Request`

when running the following code:
```java
OAuthHelper helper = reddit.getOAuthHelper();
helper.setRefreshToken("Token received from UserChallenge");

OAuthData finalData = helper.refreshToken(Credentials.installedApp("my key", "http://ccrama.me"));
reddit.authenticate(finalData);
```

Is this an issue with JRAW or an issue with how I'm trying to refresh my token?

Thanks!

**Comment by thatJavaNerd** [comment]
Can you post the HttpLogger output?

```java
redditClient.setLoggingMode(LoggingMode.ALWAYS);
```

**Comment by ccrama** [comment]
This is the output

<code>
03-22 14:53:30.732  23367-23412/me.ccrama.redditslide W/System.err﹕ java.lang.RuntimeException: Could not execute the request: HttpRequest {method='POST', url=https://www.reddit.com/api/v1/access_token, expectedMediaType=*/*, headers=User-Agent: android:me.ccrama.RedditSlide:v0.1.0 (by /u/ccrama)
03-22 14:53:30.732  23367-23412/me.ccrama.redditslide W/System.err﹕ , body=net.dean.jraw.http.RequestBody$DefaultRequestBody@301e481e}
03-22 14:53:30.738  23367-23412/me.ccrama.redditslide W/System.err﹕ at net.dean.jraw.http.RestClient.execute(RestClient.java:146)
03-22 14:53:30.738  23367-23412/me.ccrama.redditslide W/System.err﹕ at net.dean.jraw.RedditClient.execute(RedditClient.java:165)
03-22 14:53:30.738  23367-23412/me.ccrama.redditslide W/System.err﹕ at net.dean.jraw.RedditClient.execute(RedditClient.java:159)
03-22 14:53:30.739  23367-23412/me.ccrama.redditslide W/System.err﹕ at net.dean.jraw.http.oauth.OAuthHelper.refreshToken(OAuthHelper.java:288)
</code>

**Comment by thatJavaNerd** [comment]
I can get an access and refresh token and use it like you described without a problem. In all likelihood, one of these is causing your problem:

1. The string you're passing into `setRefreshToken()` is actually the access token.
3. The client ID is incorrect

**Comment by ccrama** [comment]
1. I confirmed ccrama.me is the correct URL
2. I logged the value that I put into setRefreshToken() and confirmed it was the same one returned on UserChallenge
3. I confirmed the client ID is correct

Anything else that could be causing this?

**Comment by thatJavaNerd** [comment]
Without the code, the only other thing I can think of is that the refresh token has been revoked.

**Comment by ccrama** [comment]
Can you post the exact code you are using? Maybe there is a discrepancy in mine.

**Comment by ccrama** [comment]
Here is the code I'm using

<code>
  @Override
        protected Void doInBackground(String... sub) {
            try {

                OAuthHelper helper = Colors.reddit.getOAuthHelper();
                helper.setRefreshToken(sub[0]); //I pass the token onto this method 
                OAuthData data = helper.refreshToken(Credentials.installedApp("APP ACCESS TOKEN", "http://ccrama.me"));
                Colors.reddit.authenticate(data); //reference to my RedditClient object
                
            } catch (Exception e) { //If I find an exception, revert to original authentication and tell the user there was an issue with logging in

</code>

**Comment by thatJavaNerd** [comment]
I'm not sure if this was a typo or not, but the app's client ID should be the first parameter in [`Credentials.installedApp()`](https://thatjavanerd.github.io/JRAW/docs/0.7.0.3/net/dean/jraw/http/oauth/Credentials.html#installedApp(java.lang.String,%20java.lang.String)), not the access token.

**Comment by ccrama** [comment]
The clientID is the string reddit gives you when you registered your app, correct? I probably worded that wrong. The string from https://www.reddit.com/prefs/apps

**Comment by fbis251** [comment]
![client ID vs secret](https://cloud.githubusercontent.com/assets/1300530/6812112/f777f98c-d229-11e4-8fb3-a1b699c6c9de.png)

Client ID is in green
secret is in red, but if the type of app you created is "installed app" then reddit will NOT provide a secret in your app preferences screen. Only the client ID will be available.

**Comment by ccrama** [comment]
Ok so that is working too. Seems like I have all the parts being used correctly. Is there anything else that could be wrong?

**Comment by fbis251** [comment]
You should try running your client through a proxy or enable request logging for JRAW to see the data that the network requests are sending out to make sure you have everything configured correctly.

**Comment by ccrama** [comment]
I requested logging and posted it above (one of the first comments). Anything strange you see there? I have double checked everything and still cant seem to find any issue.

**Comment by fbis251** [comment]
Here are JRAW's Logs from a simple JRAW Android test app:

    I/JRAW    ( 7574): POST https://www.reddit.com/api/v1/access_token
    I/JRAW    ( 7574):     form-data: {grant_type=refresh_token,
    I/JRAW    ( 7574):                 refresh_token=REFRESH_TOKEN}
    I/JRAW    ( 7574):     headers: {User-Agent: JrawTest 0.1}
    I/JRAW    ( 7574):     basic-auth: {password=<sensitive>,
    I/JRAW    ( 7574):                  username=CLIENT_ID}
    I/JRAW    ( 7574): SPDY/3.1 200 OK
    I/JRAW    ( 7574):     headers: {cache-control: no-cache,
    I/JRAW    ( 7574):               content-type: application/json; charset=UTF-8,
    ... MORE HEADERS ...
    I/JRAW    ( 7574):     response-body: {"access_token": "ACCESS_TOKEN", "token_type": "bearer", "expires_in": 36...
    V/MainActivity( 7574): Authenticated

REFRESH_TOKEN is a token I had previously gotten from standard OAuth session. CLIENT_ID is the public ID for an Installed App I created using reddit's developed applications page.

**Comment by fbis251** [comment]
Here is the code I used for the request:
```java
if (!mRefreshToken.isEmpty()) {
    final Credentials credentials = Credentials.installedApp(CLIENT_ID, REDIRECT_URL);
    OAuthHelper oAuthHelper = mRedditClient.getOAuthHelper();
    oAuthHelper.setRefreshToken(mRefreshToken);
    try {
        OAuthData finalData = oAuthHelper.refreshToken(credentials);
        mRedditClient.authenticate(finalData);
        if (mRedditClient.isAuthenticated()) {
            Log.v(LOG_TAG, "Authenticated");
        }
    } catch (OAuthException e) {
        e.printStackTrace();
    }
}
```

**Comment by ccrama** [comment]
Will test now. Thanks!

**Comment by ccrama** [comment]
Using exactly your code, I still get a bad request. I thought it might be just a bug with my current key, so I reset the app, re-authenticated, and retried. The key WAS the same, but the 400 bad request error still persists.

**Comment by fbis251** [comment]
How about creating a brand new test key?
Try your request from a different network or device.
Try to inspect the HTTP traffic with a proxy such as Burp.

At this point it doesn't look like it's an issue with the library.

**Comment by ccrama** [comment]
I tried a new Client ID, new network, new auth key, and still isn't working. I honestly don't know how this issue could be occurring. Bad Request to me seems like the library is sending a bad request to Reddit, but honestly if it is working for everyone else, it must be an issue with my code. I will try to work it out tonight, and will post an update later on the status

**Comment by ccrama** [comment]
I seriously have no idea what the issue is. fbis251 can you send me all the code you are using and I'll send you what I have? I might be missing something that you aren't.

**Comment by fbis251** [comment]
https://gist.github.com/fbis251/5d54e95d96fbfda22a3f

I used v0.7.0.3 of JRAW and it works fine for me, just fill in the instance variables for the class and you should be good to go.

Here are the relevant sections of my build.gradle file
```
repositories {
    jcenter()
}

dependencies {
    compile 'net.dean.jraw:JRAW:0.7.0.3'
    // debugging
    debugCompile 'org.slf4j:slf4j-android:1.7.7'
}
```

**Comment by ccrama** [comment]
Thank you so much. I will test this out when l get home. Pretty much everything looks the same except for the way you get your token from the we view and what you do with the cache. That might be my issue

**Comment by ccrama** [comment]
ITS WORKING! I have no idea what the issue was, though. Interestingly, the authentication URL contained some illegal characters making reddit return a forbidden page,        
 authorizationUrl = authorizationUrl.replace("%3A%2F%2Fi", "://www");
 worked fine for me. I dont know if that was my real issue, but it seemed to fix the problem on my end!

Cheers, and thanks!
