### ISSUE TITLE
No way to get Subscriptions?

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#60]
I can't seem to find any method to get subscribed subreddits (preferably returning a List<String> of sub names). Does one exist?

Thanks!

**Comment by fbis251** [comment]
https://thatjavanerd.github.io/JRAW/docs/git/net/dean/jraw/paginators/UserSubredditsPaginator.html

You have to use the SUBREDDITS_MINE_SUBSCRIBER endpoint

**Comment by ccrama** [comment]
Wow didn't see that page. Thanks!
