### ISSUE TITLE
setTimePeriod() on SubmissionSearchPaginator seems not to work

### ISSUE THREAD

**Issue by ccrama** [thatJavaNerd/JRAW#63]
When I run this code:
            submissionSearchPaginator.setTimePeriod(TimePeriod.valueOf("DAY")); //I do valueOf because the value might be different//
I still get results from hundreds of days before. The method seems not to work.

**Comment by thatJavaNerd** [comment]
What is `HttpLogger` producing?

To enable `HttpLogger`, use `redditClient.setLoggingMode(LoggingMode.ALWAYS)`

**Comment by ccrama** [comment]
Where does the logger post to? I can't seem to find it on the android logcat at all

**Comment by thatJavaNerd** [comment]
JRAW uses SLF4J for logging, so include an implementation of SLF4J in your dependencies that logs to the Android log like [this library](http://www.slf4j.org/android/).

**Comment by ccrama** [comment]
Sorry, haven't had much time to test this out. Will do that tomorrow and post the results. Thanks!

**Comment by fbis251** [comment]
@ccrama You can add this to your build.gradle to see the logging output:
debugCompile 'org.slf4j:slf4j-android:1.+'

**Comment by ccrama** [comment]
Will do tonight fbis

**Comment by ccrama** [comment]
Full log for a search

<code>
04-22 21:15:01.722    6537-6740/me.ccrama.redditslide I/JRAW﹕ SPDY/3.1 200 OK
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ headers: {cache-control: no-cache,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ cf-ray: 1db60ee7e0880938-DFW,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ content-type: application/json; charset=UTF-8,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ date: Thu, 23 Apr 2015 02:15:02 GMT,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ OkHttp-Received-Millis: 1429755301486,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ OkHttp-Selected-Protocol: spdy/3.1,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ OkHttp-Sent-Millis: 1429755299801,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ pragma: no-cache,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ server: cloudflare-nginx,
04-22 21:15:01.723    6537-6740/me.ccrama.redditslide I/JRAW﹕ vary: accept-encoding,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-content-type-options: nosniff,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-frame-options: SAMEORIGIN,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-moose: majestic,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-remaining: 570.0,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-reset: 299,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-used: 30,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-reddit-tracking: https://pixel.redditmedia.com/pixel/of_destiny.png?v=/ORCVDUDe8lB+QxhHJyhiQ70TukyL7QVJY/RjQ9otr7/hsVl/yNL9mYNXJgXKc3/DR/Ob48MvZLoyAQSc9yyE0Z6wmbCoCGO,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-ua-compatible: IE=edge,
04-22 21:15:01.724    6537-6740/me.ccrama.redditslide I/JRAW﹕ x-xss-protection: 1; mode=block}
04-22 21:15:01.726    6537-6740/me.ccrama.redditslide I/JRAW﹕ response-body: {"kind": "Listing", "data": {"facets": {}, "modhash": null, "children": [{"kind": "t3", "data": {...

</code>

**Comment by thatJavaNerd** [comment]
This is the output of the response, but the important part here is the request. Can you post log section pertaining to the request please?

**Comment by ccrama** [comment]
Sorry, here's the whole thing

<code>
04-23 07:12:21.364  15198-15315/me.ccrama.redditslide I/JRAW﹕ GET https://oauth.reddit.com/search?q=dogs&sort=relevance&restrict_sr=off
04-23 07:12:21.364  15198-15315/me.ccrama.redditslide I/JRAW﹕ headers: {Authorization: bearer 28243312-f6LvKUg992C7zkQ9H8KfAGOLMYA,
04-23 07:12:21.364  15198-15315/me.ccrama.redditslide I/JRAW﹕ Cache-Control: no-cache,
04-23 07:12:21.364  15198-15315/me.ccrama.redditslide I/JRAW﹕ User-Agent: android:me.ccrama.RedditSlide:v0.1.0 (by /u/ccrama)}
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ SPDY/3.1 200 OK
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ headers: {cache-control: no-cache,
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ cf-ray: 1db979ef90cb094a-DFW,
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ content-type: application/json; charset=UTF-8,
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ date: Thu, 23 Apr 2015 12:12:23 GMT,
04-23 07:12:22.571  15198-15315/me.ccrama.redditslide I/JRAW﹕ OkHttp-Received-Millis: 1429791142325,
04-23 07:12:22.572  15198-15315/me.ccrama.redditslide I/JRAW﹕ OkHttp-Selected-Protocol: spdy/3.1,
04-23 07:12:22.572  15198-15315/me.ccrama.redditslide I/JRAW﹕ OkHttp-Sent-Millis: 1429791141371,
04-23 07:12:22.572  15198-15315/me.ccrama.redditslide I/JRAW﹕ pragma: no-cache,
04-23 07:12:22.572  15198-15315/me.ccrama.redditslide I/JRAW﹕ server: cloudflare-nginx,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ vary: accept-encoding,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-content-type-options: nosniff,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-frame-options: SAMEORIGIN,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-moose: majestic,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-remaining: 593.0,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-reset: 458,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-ratelimit-used: 7,
04-23 07:12:22.573  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-reddit-tracking: https://pixel.redditmedia.com/pixel/of_destiny.png?v=MUVSovAoWhC1aOh/BN7U104BYugJ+v6PT2G6oGGXHdBlMLYgEzPhLyLCjGuoOe3rTWjHY6Y3t29qZSi8nlcFvrvyGvn37FY4,
04-23 07:12:22.574  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-ua-compatible: IE=edge,
04-23 07:12:22.574  15198-15315/me.ccrama.redditslide I/JRAW﹕ x-xss-protection: 1; mode=block}
04-23 07:12:22.575  15198-15315/me.ccrama.redditslide I/JRAW﹕ response-body: {"kind": "Listing", "data": {"facets": {}, "modhash": null, "children": [{"kind": "t3", "data": {...

</code>

**Comment by ccrama** [comment]
And this is the code. the pag variable is a Submission Search Paginator

<code>
  @Override
        protected ArrayList<Submission> doInBackground(String... data) {

            pag = new SubmissionSearchPaginator(Authentication.reddit, toget);
            if(data[1] != null && !data[1].isEmpty())
            pag.setSubreddit(data[1]);
            pag.setTimePeriod(TimePeriod.valueOf(data[0]));

            pag.setSearchSorting(SubmissionSearchPaginator.SearchSort.RELEVANCE);
            return new ArrayList<>(pag.next());
        }

</code>

I did a log print of the value of data[0] and it's "DAY"

**Comment by ccrama** [comment]
Does my code check out?

**Comment by ccrama** [comment]
Any word on this?

**Comment by thatJavaNerd** [comment]
Hey sorry it took so long for me to get back to you! I'm currently working on a patch for this. Also be sure to include a sorting (`Paginator.setSorting(Sorting)`) because reddit ignores time periods if no sorting is specified.

**Comment by ccrama** [comment]
Oh! Interesting. Thanks!
