### ISSUE TITLE
getComments() always returns null

### ISSUE THREAD

**Issue by phanghos** [thatJavaNerd/JRAW#66]
I am getting the front page perfectly with a SubredditPaginator, but for every submission in the Listing, getComments() returns null.

**Comment by thatJavaNerd** [comment]
Duplicate of #29 and #44.

See [here](https://github.com/thatJavaNerd/JRAW/issues/29#issuecomment-67701249) for an explanation.

**Comment by phanghos** [comment]
Thank you for the quick reply. I actually figured it out right after I posted the question by having a closer look at the RedditClient class.
