### ISSUE TITLE
Add removal_reason getter method to Submission and Comment

### ISSUE THREAD

**Issue by thatJavaNerd** [thatJavaNerd/JRAW#70]
As of [this announcement](https://www.reddit.com/r/announcements/comments/35uyil/transparency_is_important_to_us_and_today_we_take/), reddit will specify the reason for a post being removed. A `removal_reason` key has been added to both the post and comment JSON models. A `getRemovalReason()` should be added to the `PublicContribution` class (`Comment`'s and `Submission`'s parent class) that retrieves this value.

As far as I can tell, there are only two values for this: `"legal"` and `null`.

**Comment by zglazer** [comment]
I'm looking to dip my feet into this project. The fix sounds pretty simple to me. 

```java
    @JsonProperty
    public String getRemovalReason() {
        return data("removal_reason", String.class);
    }
```

Am I overlooking something?

**Comment by thatJavaNerd** [comment]
That's actually almost exactly what needs to be done! However the second parameter may be removed because `data(key)` and `data(key, String.class)` yield the same result.

**Comment by zglazer** [comment]
Great. I will work on this and try to get some tests for it as well.

I'm pretty green when it comes to this stuff so I REALLY appreciate your guidance and patience.
