### ISSUE TITLE
How to up/down vote a submission/comment

### ISSUE THREAD

**Issue by phanghos** [thatJavaNerd/JRAW#71]
I can't find the method for up/down voting a submission or comment. Thank you.

**Comment by fbis251** [comment]
Hey, when in doubt, check the Endpoints file, @thatJavaNerd took some time to make it easy to find what reddit API calls map out to in his library's code, for example the vote endpoint:

https://github.com/thatJavaNerd/JRAW/blob/master/ENDPOINTS.md#vote

**Comment by phanghos** [comment]
Thank you @fbis251 ! I didn't know about that file. That will help in the future too.
