### ISSUE TITLE
0.7.1 pom incorrectly named in jcenter. 

### ISSUE THREAD

**Issue by jander99** [thatJavaNerd/JRAW#72]
The 0.7.1 pom is not named properly, and maven cannot find it.

https://jcenter.bintray.com/net/dean/jraw/JRAW/0.7.1/  only has a "0.7.1.pom" and not "JRAW-0.7.1.pom" as needed by maven convention.  Version 0.7.0 works.

**Comment by thatJavaNerd** [comment]
Ok it should be fixed now!
