### ISSUE TITLE
Can't send private messages

### ISSUE THREAD

**Issue by phanghos** [thatJavaNerd/JRAW#74]
I can't send private messages with the <code>InboxManager</code> because I need a CAPTCHA and that parameter is missing in the method <code>compose()</code>.

**Comment by thatJavaNerd** [comment]
Captchas will only be asked for if your account has less than ten link karma. Please satisfy this condition first to use the endpoint without error.

**Comment by phanghos** [comment]
But where should I insert the CAPTCHA? In the <code>AccountManager</code> class, there are overloaded versions of the method <code>submit()</code>: one with CAPTCHA and one without it.

**Comment by thatJavaNerd** [comment]
You can create another `compose()` method with the Captcha and Captcha attempt parameters similarly to how it is done with [`AccountManager.submit()`](https://github.com/thatJavaNerd/JRAW/blob/5218293a4deb7a94ab0296275cdc0644318026e0/src/main/java/net/dean/jraw/managers/AccountManager.java#L68).
