### ISSUE TITLE
Anonymous mode 

### ISSUE THREAD

**Issue by DocJava** [thatJavaNerd/JRAW#79]
Anonymous mode: maybe this is me not understanding correctly, but is there a way for people to use this api without needing to sign in first? Just to view subreddits and such?

**Comment by thatJavaNerd** [comment]
What you're looking for is application-only OAuth. Basically you have access to read-only endpoints. You can see a full list in the [wiki](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2#types-of-authentication).

**Comment by DocJava** [comment]
Wow i apologize for missing that... Thanks! And any chance for an upcoming
Voat wrapper as well?

**Comment by thatJavaNerd** [comment]
It all depends on what Voat decides to do with its API. v1 is extremely limited and v2 is right around the corner so if I were to make a wrapper it would not be anytime soon.

**Comment by DocJava** [comment]
When you say v1 are you talking about
v1a: https://voat.co/api/help
or
v1b: http://fakevout.azurewebsites.net/api/help

Just wondering because I know the first one is a legacy but the second one
says v1 so I was not sure if there might have been a third one out there.

**Comment by thatJavaNerd** [comment]
I was originally referring to the legacy API, but v**2** is heard to have more features such as saving posts. I don't know how much it will differ from the current API so I don't want to start making the wrapper and then have to change it all soon after.

**Comment by DocJava** [comment]
Fair enough, if you decide to do a JVAW or a JVRAW let me know! Thanks for
the awesome API by the way!

**Comment by thatJavaNerd** [comment]
Glad I could help
