### ISSUE TITLE
Fetching authenticated user's frontpage

### ISSUE THREAD

**Issue by DVassilev** [thatJavaNerd/JRAW#83]
Hi,

How can I fetch the authenticated user's frontpage?

Thanks,
Daniel

**Comment by zglazer** [comment]
I believe you want to use the SubredditPaginator class.

**Comment by DVassilev** [comment]
@zglazer Ah okay, I just had a look at it and seems about right. Do you know how I would go about implementing it though?

**Comment by zglazer** [comment]
Look at the website in the About section. He has a short 3 line example of how to do exactly that.

**Comment by thatJavaNerd** [comment]
Snippet in question:

```java
RedditClient reddit = new RedditClient(...)
for (Submission link : new SubredditPaginator(reddit).next()) {
    System.out.printf("%s↑ /r/%s - %s\n", link.getScore(), link.getSubreddit(), link.getTitle())
}
```

Please make sure to read the [wiki page](https://github.com/thatJavaNerd/JRAW/wiki/Paginators) on Paginators. Was there anything specific about SubredditPaginator you wanted to know about?

**Comment by DVassilev** [comment]
Thank you, I ended up figuring it out.
