### ISSUE TITLE
RedditClient#getAuthenticatedUser returns null in installed app

### ISSUE THREAD

**Issue by DVassilev** [thatJavaNerd/JRAW#84]
Based on this http://thatjavanerd.github.io/JRAW/docs/latest/net/dean/jraw/RedditClient.html#getAuthenticatedUser() I expected it to return the username as it's an installed app with the 'identity' scope provided but instead it returns null.

Any ideas?

Thanks,
Daniel

**Comment by thatJavaNerd** [comment]
Can you provide the relevant code?

**Comment by DVassilev** [comment]
It's basically all from the wiki.

    redditClient = new RedditClient(UserAgent.of("android"));
    oAuthHelper = redditClient.getOAuthHelper();
    credentials = Credentials.installedApp(getString(R.string.CLIENT_ID), getString(R.string.REDIRECT_URL));

and then I authenticate it all successfully and do

    redditClient.getAuthenticatedUser();

and it returns null.

**Comment by fbis251** [comment]
What does redditClient..me().getFullName() return? Note that that performs a network call and you should call it from a background thread since I think you're using Android.

**Comment by DVassilev** [comment]
@fbis251 That works but I wanted to avoid the additional network call.

**Comment by fbis251** [comment]
You may just want to check for `redditClient.isAuthenticated()` then, since that doesn't do an extra call, but you won't be able to get the logged in user's username without `me().getFullName()`.

I'm pretty sure that `getAuthenticatedUser()` returning null isn't intentional.

@thatJavaNerd is it a bug in the library?

**Comment by DVassilev** [comment]
@fbis251 My concern isn't checking whether or not they are authenticated, I just want to get their username which is what I believe getAuthenticatedUser() does.

It seems like its a bug as I believe I have met the requirements specified on the JavaDocs to get a result.

**Comment by fbis251** [comment]
I started poking around in the library's code, and the library IS supposed to do that 2nd network call to get the username.

https://github.com/thatJavaNerd/JRAW/blob/master/src/main/java/net/dean/jraw/RedditClient.java#L122
@thatJavaNerd Changing line 122 from
`if (!authMethod.isUserless() && isAuthorizedFor(Endpoints.OAUTH_ME)) {`
to
`if (!authMethod.isUserless()) {`
does make the call to get the logged in user's username. This wouldn't be able to happen if the OAuth scope wasn't requested, so it looks like there is a bug with `isAuthorizedFor(Endpoints.OAUTH_ME)`

@DVassilev for now it looks like the workaround is to call `me().getFullName()` yourself until there is a patch in the library unless I'm wrong about the OAuth scopes

**Comment by DVassilev** [comment]
@fbis251 Yeah, that's what I have been doing but with Android extra network calls are bit of an inconvenience with threading and all.

**Comment by fbis251** [comment]
@DVassilev look at the code I linked you to, JRAW itself is supposed to use the same method to get the username. You won't be saving any resources/bandwidth if you do it yourself.

If you followed the example in the wiki, use that method in `doInBackground(...)` and you should be fine.

**Comment by DVassilev** [comment]
@fbis251 Not from a resource/bandwidth point of view but from a 'having to create an extra thread to perform the task' point of view. I have done it, it's simple - just would prefer to avoid the extra async task.

**Comment by fbis251** [comment]
@DVassilev What scopes did you use when you did your initial OAuth login?

**Comment by DVassilev** [comment]
@fbis251 I posted the scopes a few comments up.

**Comment by thatJavaNerd** [comment]
What version of the library are you using?s

**Comment by DVassilev** [comment]
The latest, v0.7.1.

**Comment by thatJavaNerd** [comment]
In that case [this commit](https://github.com/thatJavaNerd/JRAW/commit/ccb2e2565a83b32ffd4f6963c8071932c2064134) might have already fixed the problem. Can you build the jar from master and see if the problem persists?

**Comment by DVassilev** [comment]
Ah I see. I have implemented the other method already, if I go back anytime to editing that app (or you update the maven repo) I'll set it up and let you know.
