### ISSUE TITLE
Using JRAW without authenticating?

### ISSUE THREAD

**Issue by DVassilev** [thatJavaNerd/JRAW#85]
Hi,

Is it possible to use JRAW without authenticating? I'd like to access public parts of Reddit that don't require being authenticated.

Thanks,
Daniel

**Comment by thatJavaNerd** [comment]
It is possible. What you're looking for is called "application-only OAuth." There's an example on the wiki [here](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2#script-and-application-only).

**Comment by DVassilev** [comment]
Thank you.

**Comment by DVassilev** [comment]
@thatJavaNerd Actually, how do we get the device ID for #userlessApp?

**Comment by thatJavaNerd** [comment]
The device ID is an ID unique to that device. You must provide a UUID object for each device using your app.
