### ISSUE TITLE
Proguard Config

### ISSUE THREAD

**Issue by DVassilev** [thatJavaNerd/JRAW#86]
What proguard config should I use?

**Comment by thatJavaNerd** [comment]
Does the default one not work? I wasn't aware proguard needed any extra configuration for this library to work.

**Comment by DVassilev** [comment]
I tried it without any rules but got an error when trying to use. I managed to
make it work by adding quite a few rules but was wondering if you had any
recommendations.

On Sun, Sep 13, 2015 at 12:01 AM, Matthew Dean < notifications@github.com [notifications@github.com] > wrote:
Does the default one not work? I wasn't aware proguard needed any extra
configuration for this library to work.

—
Reply to this email directly or view it on GitHub
[https://github.com/thatJavaNerd/JRAW/issues/86#issuecomment-139773139] .[https://github.com/notifications/beacon/AEPX-yaFmhlkLuWIQuJrebnTAs-sRE8Lks5oxCfRgaJpZM4F8PhL.gif]

**Comment by thatJavaNerd** [comment]
I don't have anything specific. Can you post the relevant code and the errors you were getting? We might be able to put together something on the wiki about proguard.

**Comment by DVassilev** [comment]
I no longer have them but from memory the error occurred when I initialised RedditClient. I had to lots of proguard rules so I'm not sure which apply specifically to JRAW but perhaps if you tried it you will also get the same problems?

**Comment by thatJavaNerd** [comment]
Without contextual code and an environment there's really nothing I can do.

**Comment by Orbyt** [comment]
As a side note, I also had an issue with Proguard which was causing a crash when starting a connection to Reddit with this library. Adding the following to my `proguard-rules.pro` file seemed to fix it:

```
#jraw
-dontwarn net.dean.**
-keep class net.dean.** {*;}
```

See [here](http://stackoverflow.com/questions/35443555/error-when-running-signed-apk-with-proguard/35443874#35443874) for details.

**Comment by thatJavaNerd** [comment]
Do you happen to have the stack trace?

**Comment by Orbyt** [comment]
@thatJavaNerd I have the stack trace from the original error in the StackOverflow question I linked, but I didnt use the retrace tool to find the original cause.

**Comment by freundTech** [comment]
@thatJavaNerd Slide for reddit i currently trying to enable ProGuard, and we also ran into a few errors there.

We got it to work using this config, but we haven't tested everything yet.

```
#Fix net.dean.jraw.models.meta.ModelManager
-keep @interface * { *; }
-keep enum net.dean.jraw.models.meta.Model$Kind {
    **[] $VALUES;
    public *;
}
-keep class * implements net.dean.jraw.models.meta.JsonSerializer {
    *;
}

-keep class * extends net.dean.jraw.models.JsonModel {
    *;
}
```

Problems are caused by everything that is accessed with reflections. ProGuard doesn't see any calls to those functions and therefor removes them. When they are later called using reflections they throw a NoSuchField/NoSuchMethodError.

The above config could probably still be improved by just keeping the Methods/Fields needed instead of the whole classes.

We have a few stacktraces at https://github.com/ccrama/Slide/pull/2106, but not all (Currently all that are posted there are fixed by the above config)

**Comment by freundTech** [comment]
Experimented a bit more and this is the best config I could come up with:

```
-keep enum net.dean.jraw.models.meta.Model$Kind {
    public *;
}
-keep class * implements net.dean.jraw.models.meta.JsonSerializer {
    public <init>(...);
}

-keep class * extends net.dean.jraw.models.JsonModel {
    public <init>(...);
}
```

In addition to that the following ProGuard config is needed for com.fasterxml.jackson, which this depends on:

```
-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }
-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}
```

Should I send this as a PR to JRAW-Android? (JRAW-Android already has an empty ProGuard config)

**Comment by thatJavaNerd** [comment]
@freundTech I would like to leave JRAW-Android unobfuscated so that debugging for users of the library won't be a nightmare. Perhaps an addition to README.md?

**Comment by freundTech** [comment]
If I understand the way ProGuard works correctly it should only obfuscate the library if the application is obfuscated.
Using the library in an unobfuscated application should also leave the library unobfuscated.

I haven't tested that yet though. I'll check if it really works as I think it works and then report back.
