### ISSUE TITLE
Documentation for Android call

### ISSUE THREAD

**Issue by Danm72** [thatJavaNerd/JRAW#87]
On [this page](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2) the docs for the onUserChallenge call are out of date. It doesn't seem to require the REDIRECT_UTL for this call.
  ```return helper.onUserChallenge(params[0], REDIRECT_URL, creds);```

**Comment by thatJavaNerd** [comment]
Thank you for bringing this to my attention. It's now been [fixed](https://github.com/thatJavaNerd/JRAW/wiki/OAuth2/_compare/fcfe1eb1bb6e4847a70e2143d3f32290cc10ec1e...5eec893e4f3a224a28e11dc0ffeb68cd5a003df8).
