### ISSUE TITLE
Too many follow-up requests: 21

### ISSUE THREAD

**Issue by stuntguy3000** [thatJavaNerd/JRAW#89]
G'day

I am following the example, and I am getting this issue: 
![image](https://cloud.githubusercontent.com/assets/1522389/11161350/3135bb42-8aca-11e5-8cb6-b2999daf73e4.png)
![image](https://cloud.githubusercontent.com/assets/1522389/11161365/a43afbfc-8aca-11e5-834e-7ca34eed29e0.png)

Any ideas? Thanks.

**Comment by stuntguy3000** [comment]
(Line 17 is OAuthData authData = redditClient.getOAuthHelper().easyAuth(credentials); )

**Comment by thatJavaNerd** [comment]
With some experimenting, it seems that that exception is thrown when any part of the credentials is wrong. Recheck your username, password, client ID and client secret.

**Comment by stuntguy3000** [comment]
I will then will get back to you, thanks

**Comment by stuntguy3000** [comment]
Using the CURL example (https://github.com/reddit/reddit/wiki/OAuth2-Quick-Start-Example) I realized the app type should of been script. Thanks!
