### ISSUE TITLE
Allow Saving/Unsaving PublicContributions

### ISSUE THREAD

**Issue by fbis251** [thatJavaNerd/JRAW#94]
At the moment JRAW only supports saving Submissions via AccountManager, but https://www.reddit.com/dev/api/oauth#POST_api_save states that you can save both comments and submissions via the API. Do you think we should change AccountManager's call to allow saving any PublicContribution?

I wanted to run this by you @thatJavaNerd before I submitted a pull request

**Comment by thatJavaNerd** [comment]
Sounds like a good idea! I didn't know that reddit let you save comments.

**Comment by fbis251** [comment]
I opened a pull request for this:
https://github.com/thatJavaNerd/JRAW/pull/95

Do you think there's a chance you could upload a new build to jCenter? The last build of JRAW is from May 2015.

Thanks

**Comment by thatJavaNerd** [comment]
I was going to wait for a bit more content but there is [one bug fix in particular](https://github.com/thatJavaNerd/JRAW/commit/ccb2e2565a83b32ffd4f6963c8071932c2064134) that isn't in any release yet so that might be a good idea.

**Comment by thatJavaNerd** [comment]
Here's [v0.8.0](https://github.com/thatJavaNerd/JRAW/releases/tag/v0.8.0)
