### ISSUE TITLE
Getting html formatted text

### ISSUE THREAD

**Issue by YIShikunov** [thatJavaNerd/JRAW#96]
Reddit API provides both self-text and comment text formatted in html (body_html). How can i get HTML formatted submission text and comment text in JRAW?

**Comment by thatJavaNerd** [comment]
[`JsonModel.data(String)`](http://thatjavanerd.github.io/JRAW/docs/0.8.0/net/dean/jraw/models/JsonModel.html#data(java.lang.String)) will let you retrieve the value of any node in the JSON.

This will get the body HTML of a submission:

```java
Submission s = ...
String bodyHtml = s.data("body_html");
```

Same thing for a comment
