### ISSUE TITLE
Best way to get all submitted links of a user?

### ISSUE THREAD

**Issue by Ferocit** [thatJavaNerd/JRAW#97]
Hi,

I hope you don't mind that I open up an issue to ask a question.

I am trying to get all posted links by a specific user (my bot), currently that is what I am doing:

```Java
private boolean hasAlreadyPostedByMe(RssNewsEntry rss) {
    SubmissionSearchPaginator ssp = new SubmissionSearchPaginator(reddit,"author:myBotUser");
    ssp.setLimit(500);
    ssp.setTimePeriod(TimePeriod.WEEK);
    ssp.setSearchSorting(SubmissionSearchPaginator.SearchSort.NEW);

    while (ssp.hasNext()) {
        Listing<Submission> userSubmissions = ssp.next();
        for (Submission sub : userSubmissions) {
            if (sub.getUrl().equalsIgnoreCase(rss.getLink()) || sub.getTitle().equalsIgnoreCase(rss.getTitle())) {
                log.info("Already posted by me: '" + rss.getTitle() + "'");
                return true;
            }
        }
    }
    return false;
}
```

I create a SubmissionSearchPaginator and make a search by author to check if something that should get posted was already posted by me. But I am getting mixed results. Sometimes it finds a post and in the next run it doesn't.

Is there a way to just get the list of submitted links? Something that actually represents this URL: https://www.reddit.com/user/jraw_test/submitted?

Thanks...

**Comment by thatJavaNerd** [comment]
What you're looking for is the [`UserContributionPaginator`](https://thatjavanerd.github.io/JRAW/docs/latest/net/dean/jraw/paginators/UserContributionPaginator.html)

```java
UserContributionPaginator p = new UserContributionPaginator(redditClient, "submitted", "jraw_test");
```

This will access the data at https://www.reddit.com/user/jraw_test/submitted like you asked.

**Comment by Ferocit** [comment]
Thank you, must have missed that Paginator.
